name: Deploy AWS S3 static website Infrastructure

on:
  workflow_call:

jobs:
  terraform:
    name: "Terraform Infrastructure"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        # We keep Terraform files in the terraform directory.
        working-directory: ./Infra

    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v2

      - name: Use Secret in Another Workflow
        run: |
          echo "Secret from Parent Workflow 1: $TERRAFORM_PATH"
          echo "Secret from Parent Workflow 2: $DEBUG_TEST"