name: Deploy AWS S3 static website Infrastructure

on:
  workflow_call:

jobs:
  terraform:
    name: "Terraform Infrastructure"
    runs-on: ubuntu-latest
    env:
      TERRAFORM_PATH: './Infra'
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      # S3 bucket for the Terraform state
      BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
      DEBUG_TEST: ${{ secrets.TEST_SECRET }}
    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v2

      - name: Use Secret in Another Workflow
        run: |
          echo "Secret from env 1: $DEBUG_TEST"