name: Deploy AWS S3 static website Infrastructure

on:
  workflow_call:

env:
  TERRAFORM_PATH: './Infra'
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  # S3 bucket for the Terraform state
  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
  DEBUG_TEST: ${{ secrets.TEST_SECRET }}

jobs:
  terraform:
    name: "Terraform Infrastructure"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        # We keep Terraform files in the terraform directory.
        working-directory: ./Infra

    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v2

      - name: Use Secret in Another Workflow
        run: |
          echo "Secret from Parent Workflow 1: $TERRAFORM_PATH"
          echo "$DEBUG_TEST" | base64 -d > decoded_secret.txt
          cat decoded_secret.txt
          export DEBUG_TEST_VALUE=$(cat decoded_secret.txt)
          echo "The value of DEBUG_TEST_VALUE is $DEBUG_TEST_VALUE"