name: Deploy AWS S3 static website Infrastructure

on:
    push:
      branches: 
        - '*'

env:
    #verbosity setting for Terraform logs
    TF_LOG: INFO
     # Credentials for deployment to AWS
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    # S3 bucket for the Terraform state
    BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE}} 

jobs:
    Upload_file:
     name: upload index.html
     runs-on: ubuntu-latest
     
     steps:
            - name: Install AWS CLI v2
              run: |
                curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
                unzip awscliv2.zip
                sudo ./aws/install --update #update flag worked
    
            # Syncs the repo with the S3 bucket
            - name: Sync with S3 (to change bucket name, and make into variable)
              run: |
                aws s3 sync . s3://${{ vars.bucket_name }} --delete --exclude "*" --include "index.html"
            
            # can use aws s3 sync <LocalPath> <S3Uri> or <S3Uri> <LocalPath> or <S3Uri> <S3Uri>
            # represents current repo
