name: Deploy AWS S3 static website Infrastructure

on:
    pull_request:
      branches: 
        - '*'
      

env:
    #verbosity setting for Terraform logs
    TF_LOG: INFO
     # Credentials for deployment to AWS
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    # S3 bucket for the Terraform state
    BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE}} 

jobs:
    terraform:
        name: "Terraform Infrastructure"
        runs-on: ubuntu-latest
        defaults:
            run:
              shell: bash
              # We keep Terraform files in the terraform directory.
              working-directory: ./Infra
        
        steps:
            - name: Checkout the repository to the runner
              uses: actions/checkout@v2
        
            - name: Setup Terraform with specified version on the runner
              uses: hashicorp/setup-terraform@v2
              with:
                terraform_version: 1.3.0
           
            - name: Terraform init
              id: init
              run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"
        
            - name: Terraform format
              id: fmt
              run: terraform fmt -check
           
            - name: Terraform validate
              id: validate
              run: terraform validate
        
            - name: Terraform plan
              id: plan
              run: terraform plan -no-color -input=false

            - name: Terraform Apply
              if: github.ref == 'refs/heads/dev' && github.event_name == 'pull' #change env check here
              run: terraform apply -auto-approve -input=false