name: Running test yml after another
on:
    push:
        branches: [ "*" ]
env:
    TERRAFORM_PATH: './Infra'

    workflow_dispatch:

jobs:
    call-workflow1:
        uses: ./.github/workflows/debug.yml

# if this works , reference:https://stackoverflow.com/questions/73137473/how-do-i-run-githhub-actions-yaml-files-in-certain-order