name: Running test yml after another
on:
    push:
        branches: [ "*" ]

jobs:
    print-from-workflow:
        runs-on: ubuntu-latest
        env:
            TERRAFORM_PATH: './Infra'
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            # S3 bucket for the Terraform state
            BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
            DEBUG_TEST: ${{ secrets.TEST_SECRET }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

    call-workflow1:
        uses: ./.github/workflows/debug.yml

# if this works , reference:https://stackoverflow.com/questions/73137473/how-do-i-run-githhub-actions-yaml-files-in-certain-order