name: Running a yml after another
on:
    push:
        branches: [ "*" ]
env:
    TERRAFORM_PATH: './Infra'

    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3

    call-workflow1:
        uses: ./.github/workflows/terraform.yml
        secrets: inherit
        
    call-workflow2:
        if: ${{ always() }} # This will make your workflow2 executed even if workflow1 fails, remove this, if you want to run this only on success of workflow1
        needs: call-workflow1
        
        uses: ./.github/workflows/main.yml
        #uses: ./.github/workflows/main.yml@feature
        secrets: inherit
        


# if this works , reference:https://stackoverflow.com/questions/73137473/how-do-i-run-githhub-actions-yaml-files-in-certain-order